name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v5

      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - uses: actions/cache@v4
        name: Cache Loom Files
        with:
          path: .gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-jars
          path: build/libs/*.jar
